name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run Cypress 🧪
        uses: cypress-io/github-action@v2

      # TODO: check that the source file was completely covered by tests
      - name: Example with code coverage 💎
        uses: cypress-io/github-action@v2
        with:
          working-directory: examples/code-coverage

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
